### ISSUE TITLE
consider making parcera available on Clojurescript

### ISSUE THREAD

**Issue by carocad** [carocad/parcera#2]
Currently parcera requires the StringBuilder class from Java in order to make the writing process fast ( Clojure's `str` is too slow on large input).

One option mentioned by @borkdude is to use [StringBuffer](https://google.github.io/closure-library/api/goog.string.StringBuffer.html) from the google library to support the same on Clojurescript.

Depending on the performance and added complexity I should consider this as a long term goal. 

Open question:
- how can I test this ? ... my knowledge of cljs is quite limitted 🤔

**Comment by borkdude** [comment]
@carocad Welcome to check out edamame which also supports ClojureScript and uses goog StringBuffer in some places (https://github.com/borkdude/edamame/blob/9b3e825b65ec6fe0dc536988fd036e6e681813de/src/edamame/impl/parser.cljc#L67).
It also runs CLJS tests. Feel free to check it out for ideas.
