### ISSUE TITLE
Fails on chained tagged literals

### ISSUE THREAD

**Issue by SevereOverfl0w** [carocad/parcera#33]
This is perfectly valid code, but parcera cannot handle it:

```
(parcera/ast "#a #b 1")
;; =>
(:code                                                                               
 (:tag (:symbol "a") (:whitespace " ") (:parcera.core/failure "#") (:symbol "b"))    
 (:whitespace " ")                                                                   
 (:number "1"))  
```

**Comment by carocad** [comment]
I think the error was that the [Reader reference](https://clojure.org/reference/reader#tagged_literals) doesnt mention anything about nested tag so I didnt consider that case. 

It seems that the [edn spec](https://github.com/edn-format/edn#tagged-elements) takes that case into account so I would assume that Clojure is implicitedly doing that.

Should be an easy fix: https://github.com/carocad/parcera/blob/master/src/Clojure.g4#L104
