### ISSUE TITLE
Incorrectly parses unquote inside var quote

### ISSUE THREAD

**Issue by SevereOverfl0w** [carocad/parcera#40]
From `(parcera/ast "#'~a")` I expected `(:code (:var_quote (:unquote (:symbol "a"))))` but actually got `(:code (:var_quote (:symbol (:parcera.core/failure "~") "a")))`

**Comment by carocad** [comment]
@SevereOverfl0w is that even valid clojure code ? do you have a reference for it ? the current grammar is based on the example from the reader: https://clojure.org/reference/reader

which kind of hints that var quote should only work with symbols (vars)

**Comment by SevereOverfl0w** [comment]
It would only work in a macro:

```
user=> (defmacro x [a] `#'~a)
#'user/x
user=> (x inc)
#'clojure.core/inc
```

original source is https://github.com/clojure/clojure/blob/653b8465845a78ef7543e0a250078eea2d56b659/src/clj/clojure/pprint/pretty_writer.clj
