### ISSUE TITLE
consider making validation customisable

### ISSUE THREAD

**Issue by carocad** [carocad/parcera#42]
I was assuming both clojure and clojurescript to follow the reader reference implementation: https://clojure.org/reference/reader

However it seems that there are differences (both on purpose or accidental) in the way that the reader behaves.

I think that in order to avoid blowing my mind (and compromising `parcera`'s future development) I should just allow the user to be able to control how much validation they want to **enforce**. This could simply be a flag on `parcera/ast` function.

**Comment by SevereOverfl0w** [comment]
Users could validate themselves on the unvalidated ast?

**Comment by carocad** [comment]
> Users could validate themselves on the unvalidated ast?

that is always possible, therefore that "feature" already exists; though it is a gift from Clojure (immutable data structures) 😉 

My concern here is rather on the expectation side i.e. as a user of parcera I would expect certain kind of syntax to be marked as incorrect. For example: `❤️` is accepted as a symbol in Clojure but not in Clojurescript. `:http://hello.com/world` is also a similar case.

**Comment by SevereOverfl0w** [comment]
I suppose I'm more thinking that no extra argument is needed, just an extra function to validate.

**Comment by carocad** [comment]
> I suppose I'm more thinking that no extra argument is needed, just an extra function to validate.

ah, interesting insight. That is certainly an option. Thanks for the idea :)
