### ISSUE TITLE
# at start of keyword supported by clojure(script) reader

### ISSUE THREAD

**Issue by SevereOverfl0w** [carocad/parcera#54]
Both Clojure & ClojureScript support this. Found this example in Quil:

https://github.com/quil/quil/blob/2753b568bd9f43a622ccc9972c6a189563d5041b/test/cljs/quil/snippet.cljs#L31

```
(:code (:simple_keyword (:parcera.core/failure "#") "results"))
```

**Comment by SevereOverfl0w** [comment]
This is probably pretty common in cljs for hiccup elements with ids.

**Comment by carocad** [comment]
I might need to split symbols and keywords lexer rules ... there seems to be enough "special cases" for keywords to warrant it 🤔
