### ISSUE TITLE
Metadata followed by Anonymous function form

### ISSUE THREAD

**Issue by SevereOverfl0w** [carocad/parcera#62]
This is not parsed correctly: `(parcera/ast "^Callable #(println)")` produces:

```
(:code                                                                               
 (:metadata                                                                          
  (:metadata_entry (:symbol "Callable"))                                             
  (:whitespace " ")                                                                  
  (:tag (:symbol (:parcera.core/failure "(") "println") (:parcera.core/failure ")")))
)   
```

Found here in the wild: https://github.com/nrepl/nREPL/blob/15ce1e96da05cabc4cd0e40f413f5cf3a3b47d02/src/clojure/nrepl/middleware/session.clj#L67

**Comment by carocad** [comment]
I am on holidays right now and most likely wont work on this in several weeks. If you are willing to work on it I would appreciate it :)

Otherwise, please be patient 😅

**Comment by SevereOverfl0w** [comment]
I'm in no rush, and taking holiday myself 😊
