### ISSUE TITLE
Consider supporting legacy NaN Inf, etc.

### ISSUE THREAD

**Issue by SevereOverfl0w** [carocad/parcera#63]
Before Clojure added an official `##NaN`, there was literals provided in tools.reader.  The significance of this is that they were supported in ClojureScript. They seem to have stopped working with recent versions of the  ClojureScript compiler, but there are still legacy codebases around in which `NaN`, `-Inf`, `Inf` are not being read correctly.

At the least, `Inf` and `NaN` should work as symbols it would seem.

**Comment by carocad** [comment]
> At the least, Inf and NaN should work as symbols it would seem.

It seems like defining those "symbols" separatedly from `##` had some suprising side effects :/

I think the solution might be simple but it might break the output again 😞
