### ISSUE TITLE
FYI: Made alc.x-as-tests which uses parcera

### ISSUE THREAD

**Issue by sogaiu** [carocad/parcera#73]
Thanks for parcera.

I used it to make [alc.x-as-tests](https://github.com/sogaiu/alc.x-as-tests).  At the moment it helps one to use the content of `comment` blocks with appropriate content as tests:

```
(comment

  (+ 1 1)
  ;; => 2

)
```

The program will produce "derived" source by unwrapping comment blocks and rewriting certain sets of expressions as tests.  The resulting source can then be executed to run the tests and receive a report.

**Comment by carocad** [comment]
glad to hear it was useful to you.

keep up the great work :)
