### ISSUE TITLE
Octal characters

### ISSUE THREAD

**Issue by sogaiu** [carocad/parcera#78]
AFAICT, octal characters (not numbers -- e.g. `\o013`) do not appear to be used very widely (at least not based on my sampling of code on clojars).

Here is a real-world example:

https://github.com/clj-commons/camel-snake-kebab/blob/692c78fcba90c61f1c17d7f18e50d31bb0ada4d6/src/camel_snake_kebab/internals/string_separator.cljc#L37

IIUC, one can have one, two, or three octal "digits" after the `\o`, but when there are three digits, the left-most digit should be less than or equal to 3.  So for example, these work:
```
\o1
\o77
\o377
```
But this doesn't:
```
\o400
```
If it seems worth adding support for this, for parsing of the three-digit case, perhaps it is not worth trying to make the left-most digit's value constrained.

FWIW, I think some relevant code in clojure's source is:

https://github.com/clojure/clojure/blob/30a36cbe0ef936e57ddba238b7fa6d58ee1cbdce/src/jvm/clojure/lang/LispReader.java#L1218-L1227

**Comment by carocad** [comment]
thanks a lot for the link to the LispReader code. That clarified some of the doubts that I had. I think it should be simple to add support for this case based on the conditions shown in the LispReader implementation
