### ISSUE TITLE
consider splitting lexer and parser

### ISSUE THREAD

**Issue by carocad** [carocad/parcera#82]
It seems that Antlr4 has some extra functionality when the lexer and the parser are separated. One recurring problem with the current grammar is that the end of a token can be the start of the next. I am currently facing this issue in #78 where `\o387` is not valid octal but it is interpreted as octal + number `\o3 87` which is valid input.

Maybe if I could split these it would be possible to better differentiate between tokens

**Comment by sogaiu** [comment]
I think I understand your description.

IIUC, in the specific case of octal characters, I guess the downside of doing something like this:
```
fragment OCTAL_CHAR: 'o' [0-9] [0-9] [0-9];
```
is that things that are invalid (e.g. `\o387`) are recognized as valid (so no error)?

OTOH, the current grammar doesn't try to constrain the range of possibilities for "radix numbers" for which only 2-36 are valid (according to LispReader.java) in the position before the `r` (or `R`).  So `2r01` and `36rA` are valid and recognized as such, but `37rZ`though invalid is recognized as a number.

I hope I understood the situation appropriately, but if I did not seem to, please point out anything that is off.

**Comment by carocad** [comment]
yeah, this is a simular situation as that of symbols. The LispReader uses macro/whitespace characters to delimit the end of a token but that required a lookahead parser which Antlr4 doesnt do natively. So although I am able to restrict the characters in a valid octal, an invalid one is recognized as the combination of an octal + number.

See https://github.com/carocad/parcera/blob/octal/src/Clojure.g4#L185 and specially the test case: https://github.com/carocad/parcera/blob/octal/test/parcera/test_cases.cljc#L132. Although those cases should fail, they are recognized as valid.

Maybe I just need to take the bullet and let the consumer of the ast validate that but it is just not nice 😞

**Comment by sogaiu** [comment]
Thanks for the pointers to the code and clear test case.

It is indeed an unfortuate situation.

**Comment by carocad** [comment]
now I think that I might have created this problem and not antlr4. I think the issue is that this rule `input: ignore | form ;` allows a `form` to be followed by another `form`. So number-number, octal-number, etc. So maybe the solution to this could be to send the `ignore` rule to another channel and add a flag to `parcera/ast` to display it if needed. See https://stackoverflow.com/a/41753478 .... however, this seems like a rather major refactor.
