### ISSUE TITLE
Another item in eval: conditional?

### ISSUE THREAD

**Issue by sogaiu** [carocad/parcera#84]
I understand that `#=` is not encouraged, but FWIW:

```
user=> #=#?(:clj (+ 1 2) :cljr (+ 1 1))
3
```

The current rule:

```
eval: '#=' ignore* (symbol | list);
```
https://github.com/carocad/parcera/blob/1c513564fa6549fef7d39477b8bc359380f1942e/src/Clojure.g4#L146

does not list `conditional`.

**Comment by carocad** [comment]
The conditional macro seems like a pain to handle on the grammar level. Adding it to the parser rules basically allows anything on read eval since reader conditional allows (almost) anything inside 😞
