### ISSUE TITLE
Radix numbers and optional 'N' suffix

### ISSUE THREAD

**Issue by sogaiu** [carocad/parcera#85]
Radix numbers do not appear to take any optional 'N' (or 'M') suffix:
```
user=> 2r01N
Syntax error reading source at (REPL:11:0).
For input string: "1N"
user=> 2r01M
Syntax error reading source at (REPL:12:0).
For input string: "1M"
```
The current grammar appears to allow an optional 'N' suffix:
https://github.com/carocad/parcera/blob/1c513564fa6549fef7d39477b8bc359380f1942e/src/Clojure.g4#L209-L210

I confirmed the following with 1c513564fa6549fef7d39477b8bc359380f1942e:
```
user=> (require '[parcera.core :as pc])
nil
user=> (pc/ast "2r01N")
(:code (:number "2r01N"))
```

**Comment by carocad** [comment]
I based that regex on the one from [LispReader](https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/LispReader.java#L71) although I didn't take a closer look at the int matching algorithm. It seems that the Clojure team does some [magic](https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/LispReader.java#L467) when reading numbers. I will have to adapt the patterns to better reflect those cases.

Thanks for the bug report :)

**Comment by sogaiu** [comment]
Thanks for the source references!
