### ISSUE TITLE
Handling the sequence: number, discard, something

### ISSUE THREAD

**Issue by sogaiu** [carocad/parcera#86]
In `clj` I get:
```
user=> [1#_ 2]
[1]
```
In parcera I get:
```
parcera.core=> (ast "[1#_ 2]")
(:code (:vector (:symbol "1#_") (:whitespace " ") (:number "2")))
```

Possibly a bit simpler were:
```
parcera.core=> (ast "1#_ 2")
(:code (:symbol "1#_") (:whitespace " ") (:number "2"))
```
and:
```
parcera.core=> (ast "1#_2")
(:code (:symbol "1#_2"))
```

This is with: 1c513564fa6549fef7d39477b8bc359380f1942e

**Comment by sogaiu** [comment]
Some possibly related data, for things other than numbers, e.g.:
```
user=> [:a#_2]
[:a#_2]
user=> (type :a#_2)
clojure.lang.Keyword
```
Parcera agrees:
```
parcera.core=> (ast "[:a#_2]")
(:code (:vector (:keyword ":a#_2")))
```

**Comment by carocad** [comment]
This is related to `symbol` being defined without any strong boundaries; same for keyword since they use the same `allowed_name_character` pattern :/

See https://github.com/carocad/parcera/blob/master/src/Clojure.g4#L52

The problem here is that `#` is a valid character *inside* a symbol, however, a symbol is not allowed to start with a number but I have not been able to code that rule with antlr4.

This might be solved when #82 is done but I don't see a short-term solution for it; sorry.

**Comment by carocad** [comment]
@sogaiu it seems that I spoke too early. Probably I had just given up on fixing that since in the past I was unable to get it right. Seems like I learned something on the way 😉 . The changes in #88 should fix this issue. It would be great if you could confirm it before merging it.

Otherwise, just let me know if you don't have the time and I will move forward with it since the tests are passing 😄

**Comment by sogaiu** [comment]
Thanks for the heads up.

I will take a look.

**Comment by sogaiu** [comment]
For https://github.com/carocad/parcera/pull/88 I have two sets of results:

1) These look good :+1: 
```
parcera.core=> (ast "[1#_2]")
(:code (:vector (:number "1") (:discard (:number "2"))))
```
```
parcera.core=> (ast "[1#_ 2]")
(:code (:vector (:number "1") (:discard (:whitespace " ") (:number "2"))))
```

2) Perhaps a different issue:
```
parcera.core=> (ast "[+1#_ 2]")
(:code (:vector (:symbol "+1#_") (:whitespace " ") (:number "2")))
```
```
parcera.core=> (ast "[-1#_ 2]")
(:code (:vector (:symbol "-1#_") (:whitespace " ") (:number "2")))
```

My sense is that LispReader prioritizes number parsing over symbols, characters, etc.: https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/LispReader.java#L254-L307

I agree that `#` being valid inside a symbol is not helping.

**Comment by carocad** [comment]
@sogaiu thanks for the feedback. Unfortunately, it is the same issue, just a different flavour :(, see [comment](https://github.com/carocad/parcera/pull/88/files#diff-a8be01018083730422b58fdd9af5e7bdR52).

Clojure LispReader does [2 LookAhead](https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/LispReader.java#L297) to handle numbers and symbols. Although this is possible with Antlr it would not be cross-platform anymore :/

**Comment by carocad** [comment]
I just made a commit that should fix the issue shown in 2. See https://github.com/carocad/parcera/pull/88/commits/9482b31abef8436133b1443726936ea44c988301

**Comment by sogaiu** [comment]
Nice!

I confirmed that https://github.com/carocad/parcera/commit/9482b31abef8436133b1443726936ea44c988301 is working as expected here :+1: 

I did find some errors for this commit, e.g. for: https://github.com/borkdude/clj-kondo/blob/278e7c10b6f7ad1c3caba271ec1406c873d60b08/src/clj_kondo/impl/profiler.clj#L14

Here is some truncated output of `(meta (ast ,,,))`:
```
#:parcera.core{:start {:row 1, :column 0}, :end {:row 28, :column 5}, :errors ({:row 14, :column 33, :message "no viable alternative at input '#)'", :type :parser, :symbol "[@117,354:354=')',<2>,14:33]", :stack (:code :input :form :collection :list :input :form :collection :list :input :form :reader_macro :backtick :form :collection :list :input :form :collection :vector :input :form :collection :list :input :form :reader_macro :dispatch), :error #error {
 :cause nil
 :via
 [{:type org.antlr.v4.runtime.NoViableAltException
   :message nil
   :at [org.antlr.v4.runtime.atn.ParserATNSimulator noViableAlt "ParserATNSimulator.java" 2028]}]
 :trace
 [[org.antlr.v4.runtime.atn.ParserATNSimulator noViableAlt "ParserATNSimulator.java" 2028]
  [org.antlr.v4.runtime.atn.ParserATNSimulator execATN "ParserATNSimulator.java" 467]
  [org.antlr.v4.runtime.atn.ParserATNSimulator adaptivePredict "ParserATNSimulator.java" 393]
  [parcera.antlr.ClojureParser dispatch "ClojureParser.java" 1696]
...
```

**Comment by carocad** [comment]
damn, good catch. Yes, this is because of the changes from that commit. `parcera` didn't like that the second character of the symbol was a number 🙈. I need to improve that pattern.
