### ISSUE TITLE
Please consider adding a CHANGELOG

### ISSUE THREAD

**Issue by bfontaine** [carocad/parcera#95]
Hello, I bumped parcera in an old project from 0.3.1 to 0.11.5, and nothing worked anymore.
It would be great if you could add a CHANGELOG so one could check if it’s safe to bump the version or if there are breaking changes to deal with.

Thanks!

**Comment by carocad** [comment]
hey @bfontaine, sorry to hear that things broke after the update. 

I keep a changelog in the [release section](https://github.com/carocad/parcera/releases) of GitHub. Hope it helps.

**Comment by bfontaine** [comment]
Thanks, that’s indeed very helpful! Thank you for maintaining this library!
